### ISSUE TITLE
[target/gba] IWRAM overlays

### ISSUE THREAD

**Issue by asiekierka** [WonderfulToolchain/wf-issues#18]
> I think [...] overlays don't work properly
> And they seem the only [reasonable] way to have more than 32KB of iwram code 

My idea here is to offer a configuration system like so:

```toml
[overlays]
iwram = [
  ["shared", "overlay_a"],
  ["shared", "overlay_b", "overlay_c"],
  ["shared", "overlay_c", "overlay_d"]
]
```

One makes a list of all the combinations of the various IWRAM sections in memory, that they want to be accessible simultaneously, and the linkscript is dynamically generated based on that. This high-level abstraction allows breaking fine details about the linker script's operation without forcing everyone to carry their own modified link script; as well as expressing overlay relationships in a way possibly slightly more intuitive to a programmer.
